app/models.py
from .extensions import db, b_crypt, login_manager
from flask_login import UserMixin
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model,UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer(),primary_key = True)
    username = db.Column(db.String(length=30),nullable=False,unique=True)
    email = db.Column(db.String(length=50),nullable=False,unique=True)
    password_hash = db.Column(db.String(length=60),nullable=False)
    blogs = db.relationship('Blog',backref='user')
    comment = db.relationship('Comment', backref='user')

    @property
    def password(self):
        return self.password

    @password.setter
    def password(self,plain_text_password):
        self.password_hash = b_crypt.generate_password_hash(plain_text_password).decode('utf-8')

    def check_password_correction(self,attempted_password):
        return b_crypt.check_password_hash(self.password_hash,attempted_password)

class Blog(db.Model):
    __tablename__ = 'blogs'
    id = db.Column(db.Integer(),primary_key=True)
    blog = db.Column(db.String(),nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    blogs = db.Column(db.Integer(),db.ForeignKey('comments.id'))
    #posted = db.Column(db.DateTime,default=datetime.utcnow)

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer(), primary_key = True)
    comment = db.Column(db.String(),nullable=False)
    user_id = db.Column(db.Integer(),db.ForeignKey('users.id'))
    blog_id = db.relationship('Blog',backref='comments')
    
class Quote:
    def __init__(self, author, quote):
        self.author = author
        self.quote = quote

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,TextAreaField
from wtforms.validators import Length, EqualTo, Email, DataRequired,ValidationError
from ..models import User

class RegisterForm(FlaskForm):
    username = StringField(label='Username:',validators=[Length(min=3,max=15),DataRequired()])
    email = StringField(label='Email Address:',validators=[Email(), DataRequired()])
    password1 = PasswordField(label='Password:', validators=[Length(min=2), DataRequired()])
    password2 = PasswordField(label='Confirm Password:',validators=[EqualTo('password1'), DataRequired()])
    submit = SubmitField(label='Create Account')

    def validate_username(self, username_to_check):
        user = User.query.filter_by(username=username_to_check.data).first()
        if user:
            raise ValidationError('Username already exist!')

    def validate_email(self, email_to_check):
        email = User.query.filter_by(email=email_to_check.data).first()
        if email:
            raise ValidationError('Email Address already exist!')

class LoginForm(FlaskForm):
    username = StringField(label= 'Username:', validators=[DataRequired()])
    password = PasswordField(label= 'Password:', validators=[DataRequired()])
    submit = SubmitField(label='Sign in')

class BlogForm(FlaskForm):
    blog = TextAreaField(label='Please add your blog',validators=[DataRequired()])
    submit = SubmitField(label='Submit')

class CommentForm(FlaskForm):
    comment = TextAreaField(label='Please add your comment',validators=[DataRequired()])
    submit = SubmitField(label='Submit')

app/__init__.py
from flask import Flask
from .main import views
from config import config_options
from .extensions import db,b_crypt,login_manager

def create_app(config_name):
    app = Flask(__name__)

    #Initializing flask extensions
    db.init_app(app)
    b_crypt.init_app(app)
    login_manager.init_app(app)
    
    #Creating the app configurations
    app.config.from_object(config_options[config_name])

    #Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template,redirect,url_for,flash
from . import main
from .forms import RegisterForm,LoginForm,BlogForm,CommentForm
from ..models import User,Blog,Comment
from ..extensions import db
from flask_login import login_user,logout_user,current_user
from ..request import get_quote

@main.route('/')
@main.route('/home')
def index_page():
    blogs = Blog.query.all()
    comments = Comment.query.all()
    quotes = get_quote()
    return render_template('index.html',blogs=blogs,quotes=quotes,comments=comments)

@main.route('/register', methods=['GET', 'POST'])
def register_page():
    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data
        password = form.password1.data
        new_user = User(username=username,email=email,password=password)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('main.login_page'))

    if form.errors != {}:
        for err_msg in form.errors.values():
            flash(f'There was an error with creating a user: {err_msg}', category='danger')

    return render_template('register.html',form=form)

@main.route('/login', methods=['GET', 'POST'])
def login_page():
    form = LoginForm()
    if form.validate_on_submit():
        attempted_user = User.query.filter_by(username=form.username.data).first()
        if attempted_user and attempted_user.check_password_correction(attempted_password=form.password.data):
            login_user(attempted_user)
            flash(f'You are loggied in as: {attempted_user.username}',category='success')
            return redirect(url_for('main.index_page'))
        else:
            flash('Username and password are not matching! Please try again', category='danger')

    return render_template('login.html', form=form)

@main.route('/blog', methods=['GET','POST'])
def blog_page():
    form = BlogForm()
    if form.validate_on_submit():
        new_blog = Blog(blog=form.blog.data,user_id=current_user.id)
        db.session.add(new_blog)
        db.session.commit()
        return redirect(url_for('main.index_page', blogs=new_blog))

    return render_template('blog.html', form=form)

@main.route('/comment',methods=['GET','POST'])
def comment_page():
    form = CommentForm()
    if form.validate_on_submit():
        new_comment = Comment(comment=form.comment.data)
        db.session.add(new_comment)
        db.session.commit()
        return redirect(url_for('main.index_page'))
    return render_template('comment.html',form=form)

@main.route('/logout')
def logout_page():
    logout_user()
    flash('You have been logged out!',category= 'info')
    return redirect(url_for('main.index_page'))

@main.route('/delete/<int:id>', methods=['GET','POST'])
def delete(id):
    user_to_delete = Blog.query.get_or_404(id)
    db.session.delete(user_to_delete)
    db.session.commit()
    flash('Blog deleted Successfully',category='success')
    return redirect(url_for('main.index_page'))

@main.route("/delete_comment/<int:id>",methods=['GET','POST'])
def delete_comment(id):
    comment = Comment.query.get_or_404(id)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted Successfully',category='success')
    return redirect(url_for('main.index_page'))

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!--Style CSS-->
    <link rel="stylesheet" type="text/css" href="{{url_for("static", filename="style.css")}}">
    
    <title>
        {% block title %}

        {% endblock %}
    </title>
  </head>
  <body>
    <!--navbar-->
    {% block navbar %}
        {% include 'navbar.html' %}
    {% endblock %}

     <!--Error Messages-->
     {% with messages = get_flashed_messages(with_categories=true) %}
     {% if messages %}
       {% for category, message in messages %}
         <div class="alert alert-{{ category }}">
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
           {{ message }}
         </div>
       {% endfor %}
     {% endif %}
    {% endwith %}
    
    <!--Content-->
    {% block content %}

    {% endblock %}
  
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/templates/blog.html
{% extends 'base.html' %}
{% block title %}
Write your blog
{% endblock %}
{% block content %}
<div class="container">
    <h1 class="h3 mb-3 font-weight-normal">
        Blog here
    </h1>
    <div class="shadow p-3 mb-5 bg-body rounded">
        <form method="POST" class="form-control">
            {{ form.hidden_tag() }}
            <br>
            <br>
            {{ form.blog.label() }}
            {{ form.blog(class='form-control',placeholder= 'Leave your blog here:') }}
    
            <br>
            {{ form.submit(class='btn btn-lg btn-block btn-primary') }}
    
        </form>
    </div>
</div>
{% endblock %}

app/templates/comment.html
{% extends 'base.html' %}
{% block title %}
Comment page
{% endblock %}
{% block content %}
<div class="container">
    <br>
    <h1 class="h3 mb-3 font-weight-normal">
        Comment here
    </h1>
    <div class="shadow p-3 mb-5 bg-body rounded">
        <form method="POST" class="form-control">
            {{ form.hidden_tag() }}
            <br>
            
            {{ form.comment.label() }}
            {{ form.comment(class='form-control',placeholder= 'Leave your comment here:') }}
    
            <br>
            {{ form.submit(class='btn btn-lg btn-block btn-primary') }}
    
        </form>
    </div>
    
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block title %}
Home Page
{% endblock %}
{% block content %}
 <!-- REQUEST FROM QUOTE API -->
 <div class="container">
    <div class="shadow p-3 mb-5 bg-body rounded">
        <div class="card-header">
            <h3 class="text-center"><strong>Random Quote of the day</strong></h3>
        </div>
        <div class="card-body">
            <blockquote class="blockquote-reverse">
                <p>{{ quotes.quote }}</p>
                <footer>{{ quotes.author }}</footer>
            </blockquote>
        </div>
    </div>
</div>

<h2 class="h3 mb-3 font-weight-normal">
    Blogs
</h2>
{% if current_user.is_authenticated %}
{% for blog in blogs %}
<div class="container">
    <div class="shadow p-3 mb-5 bg-body rounded">
        <div class="card-body">
            <p class='card-text'>by:{{blog.user.username}}</p>
            <p class="card-text">{{ blog.blog }}</p>
            <a href="{{ url_for('main.comment_page') }}" class="btn btn-secondary">Comment</a>
            <a class =" btn btn-sm btn-danger" href="{{url_for('main.delete',id = blog.id)}}">Delete</a>
        </div>
  </div>
</div>
{% endfor %}
{% elseif %}
{% for blog in blogs %}
<div class="container">
    <div class="shadow p-3 mb-5 bg-body rounded">
        <div class="card-body">
            <p class='card-text'>by:{{blog.user.username}}</p>
            <p class="card-text">{{ blog.blog }}</p>
        </div>
  </div>
</div>
{% endfor %}
{% else %}
<div class="container">
    <div class="shadow p-3 mb-5 bg-body rounded">
        <div class="card-body">
            <p class='card-text'>There is no blogs to display</p>
        </div>
  </div>
</div>
{% endif %}
<h2 class="h3 mb-3 font-weight-normal">
    The comment section
</h2>
{% for comment in comments %}
<div class="container">
    <div class="shadow p-3 mb-5 bg-body rounded">
        <p class="card-text">{{comment.comment}}</p>
        <br>
        <a class =" btn btn-danger" href="{{url_for('main.delete_comment',id = comment.id)}}">Delete</a>
    </div>
</div>

{% endfor  %}
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% block title %}
Login
{% endblock %}
{% block content %}
<div class="login">
    <div class="container">
        <br>
        <h1 class="h3 mb-3 font-weight-normal">
            Login Here
        </h1>
        <div class="shadow p-3 mb-5 bg-body rounded">
            <form method="POST" class="form-signin">
                {{ form.hidden_tag() }}
                <br>
                {{ form.username.label() }}
                {{ form.username(class='form-control', placeholder='Username') }}
        
                {{ form.password.label() }}
                {{ form.password(class='form-control', placeholder='Username') }}
                <br>
        
                <div class="checkbox mb-3">
                    <h6>Do not have an account?</h6>
                    <a class="btn btn-sm btn-secondary" href="{{ url_for('main.register_page')}}">Register Here</a>
                </div>
        
                {{ form.submit(class='btn btn-lg btn-block btn-primary') }}
        
        
            </form>
        </div>
        
    </div>
</div>
{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{url_for('main.index_page')}}">Blog<span>ger</span></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        {% if current_user.is_authenticated %}
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link">Welcome {{current_user.username}}</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.blog_page') }}">Write a Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.logout_page') }}">Logout</a>
        </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.login_page') }}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.register_page') }}">Register</a>
            </li>
        </ul>
        {% endif %}
      </div>
    </div>
  </div>
</nav>

app/templates/register.html
{% extends 'base.html' %}
{% block title %}
Register Form
{% endblock %}
{% block content %}
<div class="register">
    <div class="container">
        <br>
        
        <h1 class="h3 mb-3 font-weight-normal">
            Please Create your account
        </h1>
        <div class="shadow p-3 mb-5 bg-body rounded">
            <form method="POST" class="form-register">
                {{ form.hidden_tag() }}
                <br>
                {{ form.username.label() }}
                {{ form.username(class='form-control',placeholder= 'Username')}}
        
                {{ form.email.label() }}
                {{ form.email(class='form-control',placeholder= 'Email Address')}}
        
                {{ form.password1.label() }}
                {{ form.password1(class='form-control',placeholder= 'Password')}}
        
                {{ form.password2.label() }}
                {{ form.password2(class='form-control',placeholder= 'Confirm Password')}}
                <br>
        
                <div class="checkbox mb-3">
                    <h6>Already have an account?</h6>
                    <a class="btn btn-sm btn-secondary" href="{{ url_for('main.login_page')}}">Login</a>
                </div>
        
                {{ form.submit(class='btn btn-lg btn-block btn-primary') }}
            </form>
        </div>
        
    </div>
</div>
{% endblock %}